services:
  - docker

language: 
  - cpp

compiler:
  - gcc

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - plk@terabee.com

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - ROS_REPO=ros
  matrix: # each line is a job
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh