services:
  - docker

compiler:
- gcc

notifications:
  email:
  on_success: always
  on_failure: always
    recipients:
      - plk@terabee.com

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - ROS_REPO=ros
  matrix: # each line is a job
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="jade"
    - ROS_DISTRO="kinetic" PRERELEASE=true
    - ROS_DISTRO="lunar"
    - ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="melodic" PRERELEASE=true

# allow failures, e.g. for unsupported distros
matrix:
  allow_failures:
    - env: ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
- source .ci_config/travis.sh